name: health
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.8.1

dependencies:
  flutter:
    sdk: flutter
  firebase_core: ^4.0.0
  firebase_database: ^12.0.0
  firebase_auth: ^6.0.1
  cloud_firestore: ^6.0.0
  provider: ^6.1.5
  http: ^1.5.0
  wifi_scan: ^0.4.1+2
  permission_handler: ^12.0.1
  web_socket_channel: ^3.0.3
  fl_chart: ^1.0.0
  mqtt_client: ^10.11.0
  intl: ^0.20.2
  shared_preferences: ^2.5.3
  flutter_launcher_icons: ^0.14.4
  

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter_launcher_icons:
  android: true
  ios: true
  image_path: "assets/images/ic_launcher_foreground.png"
  adaptive_icon_path: "assets/images/ic_launcher_foreground.png"
  image_path_ios: "assets/images/play_store_512.png"
  remove_alpha_ios: true
  adaptive_icon_background: "#011031"
  adaptive_icon_foreground: "assets/images/ic_launcher_foreground.png"
  adaptive_icon_padding: false

flutter:
  uses-material-design: true
  assets:
    - assets/images/

  fonts:
    - family: Sora
      fonts:
        - asset: assets/fonts/Sora-Light.ttf
          weight: 300
        - asset: assets/fonts/Sora-Regular.ttf
          weight: 400
        - asset: assets/fonts/Sora-Medium.ttf
          weight: 500
        - asset: assets/fonts/Sora-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/Sora-Bold.ttf
          weight: 700
        - asset: assets/fonts/Sora-ExtraBold.ttf
          weight: 800
