name: health
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.8.1

dependencies:
  flutter:
    sdk: flutter
  firebase_core: ^4.0.0
  firebase_database: ^12.0.0
  firebase_auth: ^6.0.1
  cloud_firestore: ^6.0.0
  provider: ^6.1.5
  http: ^1.5.0
  wifi_scan: ^0.4.1+2
  permission_handler: ^12.0.1
  web_socket_channel: ^3.0.3
  fl_chart: ^1.0.0
  

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/images/
